/var/log/antigateway-tunnel-check.log
/var/log/antigateway-update-routes.log
/var/log/antigateway-update-lists.log
/var/log/antigateway-install.log
{
    weekly
    rotate 8
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
}
