#!/bin/bash
# Скачивает список заблокированных IP и обновляет nftables set blocked_ips.
# Источник: antifilter.download — агрегированный список заблокированных в РФ IP.
#
# Атомарность: формируем единый nft-файл (flush set + add element) и
# применяем одной транзакцией через `nft -f` — нет окна утечки трафика
# между сбросом и восстановлением.
set -uo pipefail

NFT_TABLE="tunnel_routing"
NFT_SET="blocked_ips"
LIST_URL="https://antifilter.download/list/ipsum.lst"

# Статические IP (Telegram DC) — восстанавливаем после flush.
# Должны совпадать со списком в /usr/local/bin/update-lists.
STATIC_SUBNETS=(
    "149.154.160.0/20"
    "91.108.4.0/22"
    "91.108.8.0/22"
    "91.108.56.0/22"
    "95.161.64.0/20"
)

TMP_LIST=$(mktemp)
TMP_NFT=$(mktemp --suffix=.nft)
trap 'rm -f "$TMP_LIST" "$TMP_NFT"' EXIT

echo "[$(date '+%F %T')] Обновление списка заблокированных IP..."
if ! curl -sS --fail --max-time 60 "$LIST_URL" -o "$TMP_LIST"; then
    echo "[$(date '+%F %T')] Ошибка загрузки $LIST_URL" >&2
    exit 1
fi

# Считаем непустые/некомментарные строки (раньше `grep -c -v ^#|^` был сломан)
COUNT=$(grep -cE -v '^([[:space:]]*#|[[:space:]]*$)' "$TMP_LIST" || true)
if [[ "${COUNT:-0}" -lt 100 ]]; then
    echo "[$(date '+%F %T')] Подозрительно мало записей ($COUNT) — пропускаем" >&2
    exit 1
fi
echo "[$(date '+%F %T')] Загружено $COUNT записей"

# Формируем единый nft файл
{
    echo "# AUTO-GENERATED by update-routes — атомарный сброс"
    echo ""
    echo "flush set ip $NFT_TABLE $NFT_SET"
    echo "add element ip $NFT_TABLE $NFT_SET {"

    for subnet in "${STATIC_SUBNETS[@]}"; do
        echo "    $subnet,"
    done

    # Базовая валидация: только строки, похожие на IPv4 / CIDR
    grep -E '^[[:space:]]*[0-9]{1,3}(\.[0-9]{1,3}){3}(/[0-9]{1,2})?[[:space:]]*$' \
        "$TMP_LIST" | while IFS= read -r line; do
        echo "    ${line// /},"
    done

    echo "}"
} > "$TMP_NFT"

if nft -f "$TMP_NFT"; then
    echo "[$(date '+%F %T')] Список обновлён атомарно: $COUNT IP + ${#STATIC_SUBNETS[@]} статических"
else
    echo "[$(date '+%F %T')] Ошибка применения nft" >&2
    exit 1
fi
