#!/bin/bash
# Скачивает список заблокированных IP и обновляет nftables set
# Источник: antifilter.download — агрегированный список заблокированных в РФ IP
# v2: атомарное обновление через единый nft -f (нет окна утечки трафика)

NFT_TABLE="tunnel_routing"
NFT_SET="blocked_ips"
LIST_URL="https://antifilter.download/list/ipsum.lst"
TMP_LIST="/tmp/blocked_ips.lst"
TMP_NFT="/tmp/blocked_ips_reset.nft"

# Статические IP (Telegram DC) — восстанавливаем после flush
STATIC_SUBNETS=(
    "149.154.160.0/20"
    "91.108.4.0/22"
    "91.108.8.0/22"
    "91.108.56.0/22"
    "95.161.64.0/20"
)

echo "[$(date)] Обновление списка заблокированных IP..."
curl -s --max-time 60 "$LIST_URL" -o "$TMP_LIST" || { echo "[$(date)] Ошибка загрузки"; exit 1; }

COUNT=$(grep -c -v ^#|^ "$TMP_LIST" || true)
echo "[$(date)] Загружено $COUNT записей"

# Формируем единый nft файл — flush + статика + новые IP в одной транзакции
{
    echo "# AUTO-GENERATED by update-routes — атомарный сброс"
    echo "# Применяется как единая транзакция (netlink batch)"
    echo ""
    echo "flush set ip $NFT_TABLE $NFT_SET"
    echo ""
    echo "add element ip $NFT_TABLE $NFT_SET {"

    # Статические подсети
    for subnet in "${STATIC_SUBNETS[@]}"; do
        echo "    $subnet,"
    done

    # Динамические IP из списка
    while IFS= read -r line; do
        [[ -z "$line" || "$line" == \#* ]] && continue
        echo "    $line,"
    done < "$TMP_LIST"

    echo "}"
} > "$TMP_NFT"

# Применяем атомарно — нет окна между flush и restore
nft -f "$TMP_NFT"
RC=$?

rm -f "$TMP_NFT" "$TMP_LIST"

if [ $RC -eq 0 ]; then
    echo "[$(date)] Список обновлён атомарно: $COUNT IP-адресов/подсетей + ${#STATIC_SUBNETS[@]} статических"
else
    echo "[$(date)] Ошибка применения nft (код $RC)"
    exit 1
fi
